// Generated by scripts/generate_api_types.py from openapi.json. Do not edit.
// openapi.json sha256: 2b644dea545d292ee043de9856d84402d82936c57fcf794455b64e13603aa169

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/demo-domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Demo Domains
         * @description Built-in .example domains that scan with no network, one per grade.
         */
        get: operations["list_demo_domains_api_v1_demo_domains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent */
        get: operations["recent_api_v1_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan */
        post: operations["scan_api_v1_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan/{domain}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Scan Get */
        get: operations["scan_get_api_v1_scan__domain__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan/{domain}/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Json
         * @description Download the scan as a JSON file. Same body as ``GET /scan/{domain}``.
         */
        get: operations["export_json_api_v1_scan__domain__json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan/{domain}/narrative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Narrative
         * @description Plain-English summary, attack scenarios and remediation steps for the latest scan.
         */
        get: operations["narrative_api_v1_scan__domain__narrative_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan/{domain}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Pdf
         * @description Download the scan as a formal PDF audit report.
         */
        get: operations["export_pdf_api_v1_scan__domain__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AttackPath */
        AttackPath: {
            /** Control Exposure */
            control_exposure: {
                [key: string]: components["schemas"]["Exposure"];
            };
            /** Description */
            description: string;
            /** Enabled By */
            enabled_by: components["schemas"]["CheckName"][];
            /** @default exposed */
            exposure: components["schemas"]["Exposure"];
            fix_control: components["schemas"]["CheckName"] | null;
            /** Id */
            id: string;
            /**
             * Reason
             * @default
             */
            reason: string;
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /**
         * CheckName
         * @enum {string}
         */
        CheckName: "mx" | "spf" | "dkim" | "dmarc" | "mta_sts" | "tls_rpt" | "transport" | "bimi" | "dnssec";
        /** CheckResult */
        CheckResult: {
            /** Data */
            data: {
                [key: string]: unknown;
            };
            /** Findings */
            findings: components["schemas"]["Finding"][];
            name: components["schemas"]["CheckName"];
            /** Records */
            records: string[];
            status: components["schemas"]["CheckStatus"];
            /**
             * Summary
             * @default
             */
            summary: string;
        };
        /**
         * CheckStatus
         * @enum {string}
         */
        CheckStatus: "pass" | "warn" | "fail" | "missing" | "error" | "not_assessed";
        /** DemoDomain */
        DemoDomain: {
            /** Domain */
            domain: string;
            grade: components["schemas"]["Grade"];
            /** Story */
            story: string;
            /** Title */
            title: string;
        };
        /**
         * Exposure
         * @description How open a domain is to one attack path.
         * @enum {string}
         */
        Exposure: "exposed" | "partial" | "mitigated" | "unknown";
        /** Finding */
        Finding: {
            /**
             * Detail
             * @default
             */
            detail: string;
            /** Recommendation */
            recommendation: string | null;
            /** @default info */
            severity: components["schemas"]["Severity"];
            /** Title */
            title: string;
        };
        /**
         * Grade
         * @enum {string}
         */
        Grade: "A" | "B" | "C" | "D" | "F";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** App */
            app: string;
            /**
             * Status
             * @default ok
             */
            status: string;
            /** Version */
            version: string;
        };
        /**
         * Narrative
         * @description Plain-English account of a scan. ``source`` records who wrote it.
         */
        Narrative: {
            /** Attack Scenarios */
            attack_scenarios: string[];
            /** Domain */
            domain: string;
            /** Fallback Reason */
            fallback_reason: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Model */
            model: string | null;
            /** Remediation Steps */
            remediation_steps: components["schemas"]["RemediationStep"][];
            /** Source */
            source: string;
            /** Summary */
            summary: string;
        };
        /**
         * Remediation
         * @description The single change that removes the most attack-path risk.
         */
        Remediation: {
            /** Action */
            action: string;
            /** Closes */
            closes: string[];
            control: components["schemas"]["CheckName"];
            /** Host */
            host: string | null;
            /** Record */
            record: string | null;
            /** Record Type */
            record_type: string | null;
            /**
             * Score Gain
             * @default 0
             */
            score_gain: number;
            /** Title */
            title: string;
        };
        /** RemediationStep */
        RemediationStep: {
            /** Action */
            action: string;
            /** Finding Id */
            finding_id: string;
            /** Priority */
            priority: number;
            /**
             * Rationale
             * @default
             */
            rationale: string;
            severity: components["schemas"]["Severity"] | null;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** ScanRequest */
        ScanRequest: {
            /** Dkim Selectors */
            dkim_selectors?: string[];
            /**
             * Domain
             * @example example.com
             */
            domain: string;
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
        /** ScanResult */
        ScanResult: {
            /** Attack Matrix */
            attack_matrix: components["schemas"]["AttackPath"][];
            /** Attack Paths */
            attack_paths: components["schemas"]["AttackPath"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Domain */
            domain: string;
            one_fix: components["schemas"]["Remediation"] | null;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
            score: components["schemas"]["ScoreBreakdown"];
        };
        /** ScoreBreakdown */
        ScoreBreakdown: {
            /** Components */
            components: {
                [key: string]: number;
            };
            grade: components["schemas"]["Grade"];
            /** Not Assessed */
            not_assessed: string[];
            /** Score */
            score: number;
        };
        /**
         * Severity
         * @enum {string}
         */
        Severity: "info" | "low" | "medium" | "high" | "critical";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_demo_domains_api_v1_demo_domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DemoDomain"][];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    recent_api_v1_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_api_v1_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_get_api_v1_scan__domain__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_json_api_v1_scan__domain__json_get: {
        parameters: {
            query?: {
                dkim_selectors?: string;
            };
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    narrative_api_v1_scan__domain__narrative_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Narrative"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_pdf_api_v1_scan__domain__pdf_get: {
        parameters: {
            query?: {
                dkim_selectors?: string;
            };
            header?: never;
            path: {
                domain: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
