#!/usr/bin/env python3
"""Generate the React app's API types from the FastAPI schema.

  1. dumps app.openapi() to frontend/src/api/openapi.json
  2. runs openapi-typescript on it (in an isolated npx environment, because it needs
     TypeScript 5 while the app uses TypeScript 6)
  3. stamps schema.d.ts with the sha256 of the schema it came from

tests/test_frontend_contract.py fails if either file is stale, so the frontend can't drift
from the backend's models. Run from anywhere: `npm run gen:api` in frontend/ calls this.
"""

from __future__ import annotations

import hashlib
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
API_DIR = ROOT / "frontend" / "src" / "api"
SCHEMA_JSON = API_DIR / "openapi.json"
SCHEMA_TS = API_DIR / "schema.d.ts"
sys.path.insert(0, str(ROOT))


def openapi_json() -> str:
    from app.main import create_app

    return json.dumps(create_app().openapi(), indent=2, sort_keys=True) + "\n"


def stamp(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def main() -> None:
    API_DIR.mkdir(parents=True, exist_ok=True)
    spec = openapi_json()
    SCHEMA_JSON.write_text(spec)
    subprocess.run(
        ["npx", "--yes", "-p", "typescript@5", "-p", "openapi-typescript@7",
         "openapi-typescript", str(SCHEMA_JSON), "-o", str(SCHEMA_TS)],
        check=True, cwd=ROOT / "frontend",
    )
    generated = SCHEMA_TS.read_text()
    SCHEMA_TS.write_text(
        f"// Generated by scripts/generate_api_types.py from openapi.json. Do not edit.\n"
        f"// openapi.json sha256: {stamp(spec)}\n\n{generated}"
    )
    print(f"wrote {SCHEMA_JSON.relative_to(ROOT)} and {SCHEMA_TS.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
